apiVersion: template.openshift.io/v1
kind: Template
parameters:
  - name: APP
    description: Application name
    value: Task-Application
  - name: COMPONENT
    description: Component name
    value: backend
  - name: GITHUB_USER
    description: GitHub username
    required: true
  - name: TAG
    description: Image tag
    value: latest
objects:
  - kind: Service
    apiVersion: v1
    metadata:
      labels:
        app: ${APP}-${TAG}
        component: ${COMPONENT}
      name: ${APP}-${TAG}-${COMPONENT}
    spec:
      type: ClusterIP
      ports:
        - name: http
          port: 80
          targetPort: 3000
          protocol: TCP
      selector:
        deployment: ${APP}-${TAG}-${COMPONENT}
  
  - kind: Route
    apiVersion: route.openshift.io/v1
    metadata:
      labels:
        app: ${APP}-${TAG}
        component: ${COMPONENT}
      name: ${APP}-${TAG}-${COMPONENT}
    spec:
      port:
        targetPort: http
      to:
        kind: Service
        name: ${APP}-${TAG}-${COMPONENT}
      tls:
        termination: edge
        insecureEdgeTerminationPolicy: Redirect

  - kind: Deployment
    apiVersion: apps/v1
    metadata:
      labels:
        app: ${APP}-${TAG}
        component: ${COMPONENT}
      name: ${APP}-${TAG}-${COMPONENT}
    spec:
      replicas: 1
      strategy:
        type: RollingUpdate
        rollingUpdate:
          maxUnavailable: 0
          maxSurge: 1
      selector:
        matchLabels:
          deployment: ${APP}-${TAG}-${COMPONENT}
      template:
        metadata:
          labels:
            app: ${APP}-${TAG}
            deployment: ${APP}-${TAG}-${COMPONENT}
            component: ${COMPONENT}
        spec:
          containers:
            - name: backend
              image: 'ghcr.io/${GITHUB_USER}/${APP}-backend:${TAG}'
              imagePullPolicy: Always
              env:
                - name: LOG_LEVEL
                  value: info
                - name: POSTGRES_HOST
                  value: ${APP}-${TAG}-database
                - name: POSTGRES_DB
                  valueFrom:
                    secretKeyRef:
                      name: ${APP}-${TAG}-database
                      key: database-name
                - name: POSTGRES_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: ${APP}-${TAG}-database
                      key: database-password
                - name: POSTGRES_USER
                  valueFrom:
                    secretKeyRef:
                      name: ${APP}-${TAG}-database
                      key: database-user
                - name: NODE_ENV
                  value: production
              ports:
                - name: http
                  containerPort: 3000
                  protocol: TCP
              readinessProbe:
                httpGet:
                  path: /api/health
                  port: http
                  scheme: HTTP
                initialDelaySeconds: 15
                periodSeconds: 10
                timeoutSeconds: 5
                successThreshold: 1
                failureThreshold: 3
              livenessProbe:
                httpGet:
                  path: /api/health
                  port: http
                  scheme: HTTP
                initialDelaySeconds: 30
                periodSeconds: 20
                timeoutSeconds: 5
                failureThreshold: 3
              resources:
                limits:
                  cpu: 150m
                  memory: 150Mi
                requests:
                  cpu: 50m
                  memory: 75Mi
              securityContext:
                allowPrivilegeEscalation: false
                runAsNonRoot: true
                seccompProfile:
                  type: RuntimeDefault
                capabilities:
                  drop: ["ALL"]
          securityContext:
            runAsNonRoot: true
            seccompProfile:
              type: RuntimeDefault
          terminationGracePeriodSeconds: 30
