CREATE TABLE IF NOT EXISTS task (
  ID INT PRIMARY KEY NOT NULL,
  TASK_NAME VARCHAR(30) NOT NULL,
  TASK_DESCRIPTION VARCHAR(30) NOT NULL,
  TASK_PROGRESS VARCHAR(30) NOT NULL,
  TASK_COMPLETED DATE
);
