apiVersion: template.openshift.io/v1
kind: Template
parameters:
  - name: APP
    description: Application name
    value: Task-Application
  - name: COMPONENT
    description: Component name
    value: database
  - name: GITHUB_USER
    description: GitHub username
    required: true
  - name: TAG
    description: Image tag
    required: true
  - name: DB_PASSWORD
    description: Password for the PostgreSQL connection user
    from: '[a-zA-Z0-9]{16}'
    generate: expression
objects:
  - kind: Secret
    apiVersion: v1
    metadata:
      name: ${APP}-${TAG}-database
    stringData:
      database-name: ${APP}
      database-password: ${DB_PASSWORD}
      database-user: postgres
    type: Opaque
  - kind: Service
    apiVersion: v1
    metadata:
      labels:
        app: ${APP}-${TAG}
      name: ${APP}-${TAG}-${COMPONENT}
    spec:
      ports:
        - port: 5432
          protocol: TCP
          targetPort: 5432
      selector:
        service: ${APP}-${TAG}-${COMPONENT}
  - kind: Deployment
    apiVersion: apps/v1
    metadata:
      labels:
        app: ${APP}-${TAG}
        deployment: ${APP}-${TAG}-${COMPONENT}
      name: ${APP}-${TAG}-${COMPONENT}
    spec:
      strategy:
        type: Recreate
      selector:
        matchLabels:
          deployment: ${APP}-${TAG}-${COMPONENT}
      template:
        metadata:
          labels:
            app: ${APP}-${TAG}
            deployment: ${APP}-${TAG}-${COMPONENT}
            service: ${APP}-${TAG}-${COMPONENT}
        spec:
          containers:
            - name: ${APP}-${TAG}-${COMPONENT}
              image: 'ghcr.io/${GITHUB_USER}/${APP}-database:${TAG}'
              imagePullPolicy: Always
              env:
                - name: POSTGRES_DB
                  valueFrom:
                    secretKeyRef:
                      name: ${APP}-${TAG}-database
                      key: database-name
                - name: POSTGRES_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: ${APP}-${TAG}-database
                      key: database-password
                - name: POSTGRES_USER
                  valueFrom:
                    secretKeyRef:
                      name: ${APP}-${TAG}-database
                      key: database-user
              ports:
                - containerPort: 5432
                  protocol: TCP
              resources:
                limits:
                  cpu: 200m
                  memory: 256Mi
                requests:
                  cpu: 50m
                  memory: 128Mi
