name: Delete Merged Branches
on:
  pull_request:
    types: [closed]

jobs:
  delete-branch:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Delete branch
      if: github.event.pull_request.merged == true
      run: |
        git push origin --delete ${{ github.head_ref }}
