name: Deploy
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Deploy Database
      uses: redhat-actions/oc-apply@v1
      with:
        openshift_server: ${{ secrets.OPENSHIFT_SERVER }}
        openshift_token: ${{ secrets.OPENSHIFT_TOKEN }}
        namespace: ${{ secrets.OPENSHIFT_NAMESPACE }}
        directory: Database
        parameters: |
          -p APP=Task-Application
          -p GITHUB_USER=${{ github.actor }}
          -p TAG=${{ github.sha }}
    
    - name: Deploy Backend
      uses: redhat-actions/oc-apply@v1
      with:
        openshift_server: ${{ secrets.OPENSHIFT_SERVER }}
        openshift_token: ${{ secrets.OPENSHIFT_TOKEN }}
        namespace: ${{ secrets.OPENSHIFT_NAMESPACE }}
        directory: Backend
        parameters: |
          -p APP=your-app-name
          -p GITHUB_USER=${{ github.actor }}
          -p TAG=${{ github.sha }}
